-- ==========================================
-- Oracle Database Schema DDL for CineMatch
-- ==========================================

-- 1. Movies Catalog Table
CREATE TABLE MOVIES (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE            VARCHAR2(255) NOT NULL,
    DESCRIPTION      VARCHAR2(2000),
    RELEASE_YEAR     NUMBER(4) NOT NULL,
    POSTER_URL       VARCHAR2(500),
    BACKDROP_URL     VARCHAR2(500),
    DIRECTOR         VARCHAR2(255),
    CAST_MEMBERS     VARCHAR2(1000),
    AVERAGE_RATING   NUMBER(3,2) DEFAULT 0.0,
    IMDB_RATING      NUMBER(3,1) DEFAULT 0.0
);

-- 2. Genres mapping
CREATE TABLE MOVIE_GENRES (
    MOVIE_ID         NUMBER NOT NULL,
    GENRE            VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_GENRES_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID) ON DELETE CASCADE,
    CONSTRAINT PK_MOVIE_GENRES PRIMARY KEY (MOVIE_ID, GENRE)
);

-- 3. Users Table (Auth)
CREATE TABLE USERS (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME         VARCHAR2(100) UNIQUE NOT NULL,
    EMAIL            VARCHAR2(255) NOT NULL,
    PASSWORD         VARCHAR2(255) NOT NULL
);

-- 4. User Genre Preferences
CREATE TABLE USER_PREFERENCES (
    USER_ID          NUMBER NOT NULL,
    PREFERRED_GENRE  VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_PREF_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT PK_USER_PREFERENCES PRIMARY KEY (USER_ID, PREFERRED_GENRE)
);

-- 5. Ratings Table (1 to 5 Stars scale, max 1 rating per user per movie)
CREATE TABLE RATINGS (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    MOVIE_ID         NUMBER NOT NULL,
    SCORE            NUMBER(1) CHECK (SCORE BETWEEN 1 AND 5) NOT NULL,
    RATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_RATINGS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RATINGS_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_MOVIE_RATING UNIQUE (USER_ID, MOVIE_ID)
);

-- 6. Watchlist Table
CREATE TABLE WATCHLIST_ITEMS (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    MOVIE_ID         NUMBER NOT NULL,
    ADDED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_WATCHLIST_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WATCHLIST_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_MOVIE_WATCHLIST UNIQUE (USER_ID, MOVIE_ID)
);

-- 7. Reviews Table (Optional addition for full schema completeness)
CREATE TABLE REVIEWS (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    USERNAME         VARCHAR2(100) NOT NULL,
    MOVIE_ID         NUMBER NOT NULL,
    REVIEW_TEXT      VARCHAR2(4000) NOT NULL,
    REVIEWED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_REVIEWS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEWS_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID) ON DELETE CASCADE
);

-- 8. Episodes Table (For TV series seasons/episodes and movie main features)
CREATE TABLE EPISODES (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MOVIE_ID         NUMBER NOT NULL,
    SEASON_NUMBER    NUMBER NOT NULL,
    EPISODE_NUMBER   NUMBER NOT NULL,
    TITLE            VARCHAR2(255) NOT NULL,
    DESCRIPTION      VARCHAR2(2000),
    AIR_DATE         VARCHAR2(50),
    DURATION_MINUTES NUMBER,
    CONSTRAINT FK_EPISODES_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_MOVIE_SEASON_EPISODE UNIQUE (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER)
);

-- Indexing for performance
CREATE INDEX IDX_RATINGS_LOOKUP ON RATINGS(USER_ID, MOVIE_ID);
CREATE INDEX IDX_GENRES_LOOKUP ON MOVIE_GENRES(MOVIE_ID);
CREATE INDEX IDX_EPISODES_LOOKUP ON EPISODES(MOVIE_ID);
CREATE INDEX IDX_MOVIES_TITLE ON MOVIES(TITLE);


-- ==========================================
-- DML Seed Data with Premium TMDB Movie Posters
-- ==========================================

-- Insert Movies Catalog (with correct IMDb ratings and TMDB images)
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(1, 'Dune I', 'Paul Atreides, a brilliant young man born into a great destiny, must travel to the most dangerous planet in the universe.', 2021, 'https://image.tmdb.org/t/p/w500/roeYIqWHyVHcjWDk6SOaepNEk0y.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/zRKQW58MBEY078AxkHxEJzUskCl.jpg', 'Denis Villeneuve', 'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac', 8.0);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(2, 'Dune II', 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.', 2024, 'https://image.tmdb.org/t/p/w500/tihf8Trht9zP3scmUQfvGlAY9FU.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg', 'Denis Villeneuve', 'Timothée Chalamet, Zendaya, Rebecca Ferguson', 8.6);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(3, 'Dune III', 'The conclusion of the epic trilogy following Paul Atreides and the fate of Arrakis.', 2026, 'https://image.tmdb.org/t/p/w500/b4wekkUaxExzOeGe7hKXzhnyXHt.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/5jnVGQXsc0oXLlWD9q6KuwacWQ2.jpg', 'Denis Villeneuve', 'Timothée Chalamet, Zendaya, Florence Pugh', 8.2);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(4, 'Stranger Things', 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments and terrifying supernatural forces.', 2016, 'https://image.tmdb.org/t/p/w500/hjVNQA2a12OxkpDEOQTBMbKVZ1K.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/56v2KjBlU4XaOv9rVYEQypROD7P.jpg', 'The Duffer Brothers', 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder', 8.7);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(5, 'The Blacklist', 'A new FBI profiler, Elizabeth Keen, has her entire life uprooted when a mysterious criminal, Raymond Reddington, surrenders.', 2013, 'https://image.tmdb.org/t/p/w500/4HTfd1PhgFUenJxVuBDNdLmdr0c.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/2eIlCirgcvEwmCSYh2wDfz5Sxvz.jpg', 'Jon Bokenkamp', 'James Spader, Megan Boone', 8.0);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(6, 'Person of Interest', 'An ex-CIA agent and a mysterious billionaire prevent violent crimes in New York City.', 2011, 'https://image.tmdb.org/t/p/w500/f8aIvYk5h7Z8EP3dinCmVgQFYow.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/1UkDX6CK8hJ0oUtUycDTp5Vh9wO.jpg', 'Jonathan Nolan', 'Jim Caviezel, Taraji P. Henson, Michael Emerson', 8.5);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(7, 'Money Heist', 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros.', 2017, 'https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg', 'Álex Pina', 'Álvaro Morte, Úrsula Corberó', 8.2);

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR, POSTER_URL, BACKDROP_URL, DIRECTOR, CAST_MEMBERS, IMDB_RATING) VALUES 
(8, 'Sisu', 'When an ex-soldier who discovers gold in the Finnish wilderness attempts to take his loot into a city, Nazi soldiers try to steal it.', 2022, 'https://image.tmdb.org/t/p/w500/tzJUDVWiPIPShIQxA6wUz3bBtJv.jpg', 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/pBdQ4iorzRV2G38mdS6rzrmUfMA.jpg', 'Jalmari Helander', 'Jorma Tommila, Aksel Hennie', 6.9);


-- Insert Movie Genres Mappings
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (1, 'Sci-Fi');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (1, 'Adventure');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (1, 'Drama');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (2, 'Sci-Fi');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (2, 'Adventure');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (2, 'Action');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (3, 'Sci-Fi');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (3, 'Adventure');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (3, 'Drama');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (4, 'Sci-Fi');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (4, 'Drama');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (4, 'Fantasy');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (5, 'Crime');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (5, 'Drama');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (5, 'Mystery');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (6, 'Action');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (6, 'Crime');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (6, 'Drama');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (7, 'Action');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (7, 'Crime');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (7, 'Drama');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (8, 'Action');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (8, 'History');
INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE) VALUES (8, 'War');

-- Insert Seed Data for Episodes
-- Movies (Single Feature Length Episode)
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (1, 1, 1, 'Part One', 'Paul Atreides, a brilliant and gifted young man born into a great destiny, must travel to the most dangerous planet in the universe.', '2021-10-22', 155);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (2, 1, 1, 'Part Two', 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.', '2024-03-01', 166);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (3, 1, 1, 'Part Three', 'The final chapter of Paul Atreides journey on the desert planet Arrakis.', '2026-05-15', 170);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (8, 1, 1, 'Sisu Main Feature', 'An ex-soldier discovers gold in the wilderness of Lapland and must protect his find from a Nazi death squad.', '2023-04-28', 91);

-- TV Show: Stranger Things (ID 4)
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (4, 1, 1, 'Chapter One: The Vanishing of Will Byers', 'On his way home from a friend''s house, young Will sees something terrifying. Nearby, a secret government lab unleashes a dark force.', '2016-07-15', 47);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (4, 1, 2, 'Chapter Two: The Weirdo on Maple Street', 'Lucas, Mike and Dustin try to talk to the girl they found in the woods. Hopper questions an anxious Joyce about a phone call.', '2016-07-15', 55);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (4, 1, 3, 'Chapter Three: Holly, Jolly', 'An increasingly concerned Joyce associates Will''s presence with flashing Christmas lights. Nancy looks for Barb.', '2016-07-15', 51);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (4, 1, 4, 'Chapter Four: The Body', 'Refusing to believe Will is dead, Joyce tries to connect with her son. The boys give Eleven a makeover.', '2016-07-15', 50);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (4, 1, 5, 'Chapter Five: The Flea and the Acrobat', 'Hopper breaks into the laboratory, while Nancy and Jonathan confront the force that took Will.', '2016-07-15', 53);

-- TV Show: The Blacklist (ID 5)
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (5, 1, 1, 'Pilot', 'Former government agent Raymond "Red" Reddington surrenders to the FBI and insists on speaking only to a newly minted profiler.', '2013-09-23', 45);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (5, 1, 2, 'The Freelancer (No. 145)', 'Red and Liz work together to track down an assassin who disguises his murders as large-scale industrial disasters.', '2013-09-30', 43);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (5, 1, 3, 'Wujing (No. 84)', 'Red recruits Liz to help encrypt intelligence for a Chinese spy, while secret agents monitor Liz''s home.', '2013-10-07', 43);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (5, 1, 4, 'The Stewmaker (No. 161)', 'While Liz testifies against a drug lord, Red warns her that a legendary assassin known as the Stewmaker is in town.', '2013-10-14', 44);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (5, 1, 5, 'The Courier (No. 85)', 'Red informs the FBI team that an intermediary known as the Courier is delivering a package to an Iranian spy.', '2013-10-21', 43);

-- TV Show: Person of Interest (ID 6)
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (6, 1, 1, 'Pilot', 'Billionaire Harold Finch recruits former CIA operative John Reese to help prevent crimes using a surveillance artificial intelligence.', '2011-09-22', 44);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (6, 1, 2, 'Ghosts', 'Reese and Finch must protect a teenager who was declared dead two years ago after her family was murdered.', '2011-09-29', 43);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (6, 1, 3, 'Mission Creep', 'The Machine identifies a former soldier who has turned to robbing bank vaults, leading Reese to infiltrate the gang.', '2011-10-06', 43);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (6, 1, 4, 'Cura Te Ipsum', 'Reese tracks a doctor who is planning to seek violent revenge against the serial rapist who drove her sister to suicide.', '2011-10-13', 43);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (6, 1, 5, 'Judgement', 'Reese and Finch try to protect a judge whose son has been kidnapped by a gang to force him to dismiss a case.', '2011-10-20', 43);

-- TV Show: Money Heist (ID 7)
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (7, 1, 1, 'Efectuar lo acordado', 'The Professor recruits a young female robber and seven other criminals for a heist on the Royal Mint of Spain.', '2017-05-02', 48);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (7, 1, 2, 'Imprudencias letales', 'The Professor guides the team through negotiations with Raquel Murillo. Internal tensions rise inside the Mint.', '2017-05-09', 43);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (7, 1, 3, 'Errar al disparar', 'Raquel searches for the identity of the Professor. Moscow tries to dig the tunnel, while Berlin enforces order.', '2017-05-16', 45);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (7, 1, 4, 'Caballo de Troya', 'The police sends a medical team inside the Mint, presenting an opportunity for the Professor to wiretap them.', '2017-05-23', 44);
INSERT INTO EPISODES (MOVIE_ID, SEASON_NUMBER, EPISODE_NUMBER, TITLE, DESCRIPTION, AIR_DATE, DURATION_MINUTES) VALUES (7, 1, 5, 'El día de la marmota', 'The Professor must clean up evidence left in a junkyard before the police can match it to him.', '2017-05-30', 42);

COMMIT;
