spring.application.name=movie-recommendation-system

# Server Port
server.port=${PORT:8080}

# H2 Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/moviedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Hibernate DDL Auto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File upload properties if needed
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Oracle APEX ORDS API Configuration
oracle.apex.api.url=${ORACLE_APEX_API_URL:https://apex.oracle.com/ords/tr_a855_sql_s40/api}

# Actuator Monitoring
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
